allow_equivalents: all
catalog_file: catalog-v001.xml
components: null
contact: null
contributors: null
creators: null
description: Ontology about the skeletomuscular system of insects
dosdp_tools_options: --obo-prefixes=true
edit_format: owl
exclude_tautologies: structural
export_formats:
- owl
- obo
- json
git_user: ''
github_org: obophenotype
gzip_main: false
id: aism
import_group:
  directory: imports/
  disabled: false
  ids: null
  products:
  - description: null
    id: ro
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  rebuild_if_source_changes: true
import_pattern_ontology: false
license: CC-BY
namespaces:
- http://purl.obolibrary.org/obo/AISM_
obo_format_options: ''
pattern_group: null
pattern_pipelines_group: null
primary_release: full
public_release: none
public_release_assets: null
reasoner: ELK
release_artefacts:
- base
- full
- simple
release_date: false
repo: anatomy_ontology_of_insect_skeletomuscular_system
report_fail_on: none
robot_java_args: -Xmx8G
robot_settings: null
robot_version: null
robotemplate_group: null
subset_group: null
title: Anatomy Ontology of Insect Skeletomuscular System
travis_emails: null
uribase: http://purl.obolibrary.org/obo
use_dosdps: false
use_external_date: false
